DROP DATABASE IF EXISTS pokebarter;
/* Creo la base de datos */
CREATE DATABASE pokebarter;

USE pokebarter; 
/* Creo la tabla para almacenar users. */
CREATE TABLE user(
    username VARCHAR(30)  PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
    nombre VARCHAR(20),
    apellido VARCHAR(30),
    telefono VARCHAR(15),
    contraseña VARCHAR(50) NOT NULL,
    datos_adicionales VARCHAR(200),
    img  VARCHAR(200)
);
/* Creo la tabla para almacenar pokémon. */
CREATE TABLE pokemon (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pokemon VARCHAR(30) NOT NULL,
    movimiento_1 VARCHAR(50),
    movimiento_2 VARCHAR(50),
    movimiento_3 VARCHAR(50),
    movimiento_4 VARCHAR(50),
    habilidad VARCHAR(50),
    nivel INT(3),
    shiny BOOLEAN NOT NULL,
    user VARCHAR(30) NOT NULL,
    estado VARCHAR(1) NOT NULL,
    juego VARCHAR(30) NOT NULL,
    img  VARCHAR(200) NOT NULL,
    FOREIGN KEY (user) REFERENCES user(username)
);

/* Inserto datos en la tabla de user */
INSERT INTO user (username, email, nombre, apellido, telefono, contrasenia, datos_adicionales, img) VALUES
('juanp', 'juan@example.com', 'Juan', 'Pérez', '1234567890', 'contrasenia1', 'Mi pokémon favorito es Gardevoir, acepto lo que sea que tenga que ver con Gardevoir', 'mggi7qzd6j331.png'),
('badgyal', 'badgyal@example.com', 'Bad Gyal', '', '', 'contrasenia2', 'Cuando yo te bailo sé que tú te vuelves loco, especialmente si te lo hago poco a poco', '17068236242241.jpeg'),
('carlosl', 'carlos@example.com', 'Carlos', 'González', '2345678901', '', 'Sólo juego Pokémon GO, no me interesa ningún otro trato.', ''),
('meili', 'meili@example.com', 'Mei', 'Li', '', 'contrasenia4', 'こんにちは (Konnichiwa!). Obvio como soy asiática juego Pokémon. ', '8d83ab32055728518588751b524543c1.jpg'),
('luisg', 'luis@example.com', 'Luis', 'Gómez', '4567890123', 'contrasenia5', 'No sólo cambio mis pokémon por otros pokémon, podemos hacer tratos', '23456789098765werdfghj.jpg'),
('sofiaf', 'sofia@example.com', 'Sofía', 'Fernández', '', 'contrasenia6', 'Contáctame en mi instagram: @lasofisticada', ''),
('jorgeh', 'jorge@example.com', 'Jorge', 'Hernández', '6789012345', 'contrasenia7', '', ''),
('luciar', 'lucia@example.com', 'Lucía', 'Ruiz', '7890123456', 'contrasenia8', 'Uwu', '319900486134136832_35s_d.jpg'),
('migueld', 'miguel@example.com', 'Miguel', 'Díaz', '', 'contrasenia9', 'También busco reunirme para jugar.', '5970028_1280.jpg'),
('andreas', 'andrea@example.com', 'Andrea', 'Santos', '9012345678', 'contrasenia10', '', 'depositphotos_582351880-stock-photo-latina-girl-holding-her-long.jpg'),
('seogonzalez', 'sergioagrvi@gmail.com', 'Sergio', 'González Rojas', '', '1234', 'Ig: seogonzalez', '1716389693391-1711147417044.jpg'),
('pokebarter', 'pokebarter@example.com', 'Nomber', 'Apellido', '', 'contrasenia9', '', '');

/* Inserto datos en la tabla de pokémon */
INSERT INTO pokemon (pokemon, movimiento_1, movimiento_2, movimiento_3, movimiento_4, habilidad, nivel, shiny, user, estado, juego, sexo, img) VALUES ('Sableye', 'Knock Off', 'Recover', 'Will-O-Wisp', '', '', '3', 0, 'juanp', 'ofrecido', 'Pokémon Ruby', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/302.png'), 
('Bagon', 'Dragon Claw', 'Crunch', 'Dragon Dance', 'Fire Fang', '', '5', 1, 'badgyal', 'solicitado', 'Pokémon Ultra Sun', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/371.png'), 
('Magnezone', 'Thunderbolt', 'Flash Cannon', 'Volt Switch', 'Hidden Power', '', '7', 0, 'carlosl', 'ofrecido', 'Pokémon Ultra Moon', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/462.png'), 
('Munchlax', 'Body Slam', 'Recycle', 'Curse', 'Self-Destruct', '', '11', 1, 'meili', 'solicitado', 'Pokémon Sun', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/446.png'), 
('Roselia', 'Giga Drain', 'Sludge Bomb', 'Toxic Spikes', '', '', '13', 0, 'luisg', 'ofrecido', 'Pokémon X', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/315.png'), 
('Lucario', 'Close Combat', 'Aura Sphere', '', '', '', '61', 1, 'badgyal', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/448.png'), 
('Gardevoir', 'Psychic', 'Moonblast', '', '', '', '53', 0, 'luisg', 'ofrecido', 'Pokémon Go', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png'), 
('Tyranitar', 'Stone Edge', 'Crunch', 'Earthquake', 'Dragon Dance', '', '67', 1, 'sofiaf', 'solicitado', 'Pokémon Ultra Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/248.png'), 
('Sylveon', 'Hyper Voice', 'Moonblast', ' ', '', '', '49', 0, 'jorgeh', 'ofrecido', 'Pokémon Go', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/700.png'), 
('Charizard', 'Flamethrower', 'Dragon Claw', '', '', '', '55', 1, 'luciar', 'solicitado', 'Pokémon Go', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png'), 
('Lopunny', 'Return', 'High Jump Kick', 'Ice Punch', 'Healing Wish', '', '17', 1, 'sofiaf', 'solicitado', 'Pokémon Alpha Sapphire', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/428.png'), 
('Budew', 'Magical Leaf', 'Toxic', 'Synthesis', 'Stun Spore', '', '19', 0, 'jorgeh', 'ofrecido', 'Pokémon Sun', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/406.png'), 
('Garchomp', 'Dragon Claw', 'Earthquake', 'Stone Edge', 'Fire Fang', '', '23', 1, 'luciar', 'solicitado', 'Pokémon Ultra Moon', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/445.png'), 
('Mismagius', 'Shadow Ball', 'Dazzling Gleam', 'Nasty Plot', 'Psychic', '', '29', 0, 'migueld', 'ofrecido', 'Pokémon Y', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/429.png'), 
('Drapion', 'Cross Poison', 'Earthquake', 'Aqua Tail', 'Knock Off', '', '31', 1, 'andreas', 'solicitado', 'Pokémon Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/452.png'), 
('Swampert', 'Earthquake', 'Waterfall', 'Ice Punch', '', '', '47', 0, 'badgyal', 'solicitado', 'Pokémon Alpha Sapphire', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png'), 
('Chandelure', 'Shadow Ball', 'Flamethrower', '', '', '', '61', 1, 'pokebarter', 'ofrecido', 'Pokémon White', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/609.png'), 
('Greninja', 'Water Shuriken', 'Dark Pulse', 'Extrasensory', 'Ice Beam', '', '72', 0, 'pokebarter', 'solicitado', 'Pokémon X', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/658.png'), 
('Heliolisk', 'Thunderbolt', 'Hyper Beam', 'Grass Knot', 'Dark Pulse', '', '68', 1, 'pokebarter', 'ofrecido', 'Pokémon Y', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/695.png'), 
('Talonflame', 'Brave Bird', 'Flare Blitz', 'Steel Wing', 'Roost', '', '64', 0, 'pokebarter', 'solicitado', 'Pokémon Omega Ruby', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/663.png'), 
('Hawlucha', 'Flying Press', 'High Jump Kick', '', '', '', '60', 1, 'pokebarter', 'ofrecido', 'Pokémon Alpha Sapphire', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/701.png'), 
('Dragalge', 'Dragon Pulse', 'Sludge Bomb', '', '', '', '59', 0, 'pokebarter', 'solicitado', 'Pokémon Ultra Sun', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/691.png'), 
('Gogoat', 'Horn Leech', 'Earthquake', '', '', '', '55', 1, 'pokebarter', 'ofrecido', 'Pokémon Ultra Moon', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/673.png'), 
('Gourgeist', 'Seed Bomb', 'Phantom Force', '', '', '', '53', 0, 'pokebarter', 'solicitado', 'Pokémon Ultra Moon', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/711.png'), 
('Heliolisk', 'Thunderbolt', 'Hyper Beam', 'Grass Knot', '', '', '68', 1, 'pokebarter', 'ofrecido', 'Pokémon Ultra Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/695.png'), 
('Lanturn', 'Thunderbolt', 'Surf', '', '', '', '59', 0, 'pokebarter', 'solicitado', 'Pokémon Alpha Sapphire', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/171.png'), 
('Haxorus', 'Dragon Claw', 'Earthquake', '', '', '', '63', 1, 'pokebarter', 'ofrecido', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/612.png'), 
('Gourgeist', 'Seed Bomb', 'Phantom Force', '', '', '', '53', 0, 'pokebarter', 'solicitado', 'Pokémon Legends Arceus', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/711.png'), 
('Tyrantrum', 'Rock Slide', 'Dragon Claw', '', '', '', '65', 1, 'pokebarter', 'ofrecido', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/697.png'), 
('Gogoat', 'Horn Leech', 'Earthquake', '', '', '', '55', 0, 'pokebarter', 'solicitado', 'Pokémon X', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/673.png'), 
('Lanturn', 'Thunderbolt', 'Surf', '', '', '', '59', 1, 'pokebarter', 'ofrecido', 'Pokémon Ultra Moon', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/171.png'), 
('Excadrill', 'Earthquake', 'Iron Head', '', '', '', '57', 0, 'pokebarter', 'solicitado', 'Pokémon Black', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/530.png'), 
('Chandelure', 'Shadow Ball', 'Flamethrower', '', '', '', '61', 1, 'pokebarter', 'ofrecido', 'Pokémon White', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/609.png'), 
('Togekiss', 'Air Slash', 'Aura Sphere', 'Thunder Wave', 'Roost', '', '53', 1, 'migueld', 'ofrecido', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/468.png'), 
('Gyarados', 'Waterfall', 'Ice Fang', 'Earthquake', 'Dragon Dance', '', '59', 0, 'andreas', 'solicitado', 'Pokémon Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png'), 
('Infernape', 'Flare Blitz', 'Close Combat', 'Thunder Punch', '', '', '43', 1, 'jorgeh', 'ofrecido', 'Pokémon Omega Ruby', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/392.png'), 
('Mimikyu', 'Play Rough', 'Shadow Claw', 'Swords Dance', 'Leer', 'Disguise', '37', 0, 'migueld', 'solicitado', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/778.png'), 
('Lucario', 'Close Combat', 'Aura Sphere', 'Flash Cannon', '', '', '61', 1, 'badgyal', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/448.png'), 
('Gardevoir', 'Psychic', 'Moonblast', '', '', '', '53', 0, 'luisg', 'ofrecido', 'Pokémon Go', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png'), 
('Tyranitar', 'Stone Edge', 'Crunch', 'Earthquake', 'Dragon Dance', '', '67', 1, 'sofiaf', 'solicitado', 'Pokémon Ultra Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/248.png'), 
('Sylveon', 'Hyper Voice', 'Moonblast', '', '', '', '49', 0, 'jorgeh', 'ofrecido', 'Pokémon Go', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/700.png'), 
('Charizard', 'Flamethrower', 'Dragon Claw', 'Air Slash', '', '', '55', 1, 'luciar', 'solicitado', 'Pokémon Go', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png'),
('Hippowdon', 'Earthquake', 'Slack Off', 'Stealth Rock', 'Stone Edge', '', '37', 0, 'seogonzalez', 'ofrecido', 'Pokémon Omega Ruby', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/450.png'), 
('Toxicroak', 'Poison Jab', 'Sucker Punch', 'Swords Dance', 'Gunk Shot', '', '41', 1, 'pokebarter', 'solicitado', 'Pokémon Ultra Moon', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/454.png'), 
('Yanmega', 'Bug Buzz', 'Air Slash', 'U-turn', 'Protect', '', '43', 0, 'juanp', 'ofrecido', 'Pokémon X', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/469.png'), 
('Serperior', 'Leaf Storm', 'Dragon Pulse', 'Hidden Power', 'Leech Seed', '', '47', 1, 'badgyal', 'solicitado', 'Pokémon Moon', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/497.png'), 
('Gigalith', 'Stone Edge', 'Earthquake', 'Heavy Slam', 'Explosion', '', '53', 0, 'carlosl', 'ofrecido', 'Pokémon Ultra Sun', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/526.png'), 
('Krookodile', 'Earthquake', 'Crunch', 'Outrage', 'Taunt', '', '59', 1, 'meili', 'solicitado', 'Pokémon Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/553.png'), 
('Pikachu', 'Thunderbolt', 'Quick Attack', '', '', '', '37', 0, 'meili', 'solicitado', 'Pokémon Go', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png'), 
('Gengar', 'Shadow Ball', 'Sludge Bomb', '', '', '', '43', 1, 'carlosl', 'ofrecido', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/94.png'), 
('Dragonite', 'Dragon Claw', 'Outrage', 'Earthquake', '', '', '61', 0, 'migueld', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png'), 
('Venusaur', 'Solar Beam', 'Sludge Bomb', 'Earthquake', '', '', '59', 1, 'sofiaf', 'ofrecido', 'Pokémon Go', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/female/3.png'), 
('Salamence', 'Dragon Claw', 'Dragon Dance', '', '', '', '65', 0, 'jorgeh', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/373.png'), 
('Gyarados', 'Waterfall', 'Ice Fang', '', '', '', '59', 0, 'andreas', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png'), 
('Swampert', 'Earthquake', 'Waterfall', 'Ice Punch', '', '', '47', 0, 'badgyal', 'solicitado', 'Pokémon Go', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png'), 
('Togekiss', 'Air Slash', 'Aura Sphere', 'Thunder Wave', 'Roost', '', '53', 1, 'migueld', 'ofrecido', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/468.png'), 
('Infernape', 'Flare Blitz', 'Close Combat', 'Thunder Punch', '', '', '43', 1, 'jorgeh', 'ofrecido', 'Pokémon Omega Ruby', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/392.png'), 
('Mimikyu', 'Play Rough', 'Shadow Claw', 'Swords Dance', 'Leer', 'Disguise', '37', 0, 'migueld', 'solicitado', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/778.png'), 
('Lucario', 'Close Combat', 'Aura Sphere', 'Flash Cannon', '', '', '61', 1, 'badgyal', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/448.png'), 
('Gardevoir', 'Psychic', 'Moonblast', '', '', '', '53', 0, 'luisg', 'ofrecido', 'Pokémon Go', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png'), 
('Gothitelle', 'Psychic', 'Shadow Ball', 'Thunderbolt', 'Calm Mind', '', '61', 0, 'luisg', 'ofrecido', 'Pokémon X', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/576.png'), 
('Talonflame', 'Brave Bird', 'Flare Blitz', 'Swords Dance', 'Roost', '', '67', 1, 'sofiaf', 'solicitado', 'Pokémon Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/663.png'), 
('Goodra', 'Dragon Pulse', 'Sludge Wave', 'Thunderbolt', 'Fire Blast', '', '71', 0, 'jorgeh', 'ofrecido', 'Pokémon Ultra Moon', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/706.png'), 
('Decidueye', 'Spirit Shackle', 'Leaf Blade', 'Sucker Punch', '', '', '73', 1, 'luciar', 'solicitado', 'Pokémon Shield', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/724.png'), 
('Infernape', 'Flare Blitz', 'Close Combat', 'Thunder Punch', '', '', '43', 1, 'jorgeh', 'ofrecido', 'Pokémon Ultra Moon', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/392.png'), 
('Gyarados', 'Waterfall', 'Ice Fang', 'Earthquake', '', '', '59', 0, 'andreas', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png'), 
('Swampert', 'Earthquake', 'Waterfall', 'Ice Punch', '', '', '47', 0, 'badgyal', 'solicitado', 'Pokémon Go', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png'), 
('Togekiss', 'Air Slash', 'Aura Sphere', 'Thunder Wave', 'Roost', '', '53', 1, 'migueld', 'ofrecido', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/468.png'), 
('Mimikyu', 'Play Rough', 'Shadow Claw', 'Swords Dance', 'Leer', 'Disguise', '37', 0, 'migueld', 'solicitado', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/778.png'), 
('Boltund', 'Spark', 'Crunch', '', '', 'Strong Jaw', '55', 1, 'jorgeh', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/836.png'), 
('Raboot', 'Double Kick', 'Flame Charge', '', '', 'Blaze', '43', 0, 'sofiaf', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/814.png'), 
('Drednaw', 'Liquidation', 'Rock Slide', '', '', 'Strong Jaw', '47', 1, 'sofiaf', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/834.png'), 
('Thievul', 'Snarl', '', '', '', 'Run Away', '51', 0, 'luciar', 'solicitado', 'Pokémon Sword', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/828.png'), 
('Eldegoss', 'Energy Ball', '', '', '', 'Cotton Down', '45', 1, 'luciar', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/830.png'), 
('Carkol', 'Flame Charge', 'Rock Blast', '', '', 'Steam Engine', '41', 1, 'seogonzalez', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/838.png'), 
('Hattrem', 'Psychic', '', '', '', 'Magic Bounce', '39', 1, 'seogonzalez', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/857.png'), 
('Charizard', 'Flamethrower', 'Dragon Claw', '', '', '', '55', 1, 'luciar', 'solicitado', 'Pokémon Go', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png'), 
('Pikachu', 'Thunderbolt', 'Quick Attack', ' ', '', '', '37', 0, 'meili', 'solicitado', 'Pokémon Go', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png'), 
('Gengar', 'Shadow Ball', 'Sludge Bomb', '', '', '', '43', 1, 'carlosl', 'ofrecido', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/94.png'), 
('Dragonite', 'Dragon Claw', 'Outrage', '', '', '', '61', 0, 'migueld', 'solicitado', 'Pokémon Go', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png'), 
('Venusaur', 'Solar Beam', 'Sludge Bomb', '', '', '', '59', 1, 'sofiaf', 'ofrecido', 'Pokémon Go', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/female/3.png'),
('Zapdos', 'Thunderbolt', 'Hurricane', 'Roost', 'Defog', '', '73', 1, 'meili', 'ofrecido', 'Pokemon X', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/145.png'), 
('Tyranitar', 'Stone Edge', 'Crunch', 'Earthquake', 'Dragon Dance', '', '67', 0, 'luisg', 'solicitado', 'Pokémon Ultra Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/248.png'), 
('Snorlax', 'Body Slam', 'Earthquake', 'Crunch', 'Rest', 'Immunity', '55', 1, 'jorgeh', 'ofrecido', 'Pokémon X', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/143.png'), 
('Alakazam', 'Psychic', 'Shadow Ball', 'Focus Blast', 'Calm Mind', 'Magic Guard', '57', 0, 'jorgeh', 'solicitado', 'Pokémon Y', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png'), 
('Silicobra', 'Wrap', 'Sand Attack', '', '', 'Sand Spit', '27', 1, 'badgyal', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/843.png'), 
('Drizzile', 'Water Pulse', '', '', '', 'Torrent', '31', 1, 'luisg', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/814.png'), 
('Thievul', 'Snarl', '', '', '', 'Unburden', '51', 1, 'luisg', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/828.png'), 
('Carkol', 'Flame Charge', 'Rock Blast', '', '', 'Flame Body', '41', 1, 'jorgeh', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/838.png'), 
('Chewtle', 'Bite', '', '', '', 'Strong Jaw', '23', 1, 'jorgeh', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/833.png'), 
('Applin', 'Withdraw', '', '', '', 'Ripen', '27', 0, 'sofiaf', 'solicitado', 'Pokémon Sword', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/840.png'), 
('Arrokuda', 'Peck', 'Aqua Jet', '', '', 'Swift Swim', '25', 1, 'sofiaf', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/846.png'), 
('Gyarados', 'Waterfall', 'Ice Fang', 'Earthquake', 'Dragon Dance', 'Intimidate', '59', 1, 'luisg', 'ofrecido', 'Pokémon Omega Ruby', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/130.png'), 
('Appletun', 'Dragon Pulse', 'Solar Beam', 'Recover', 'Iron Defense', 'Ripen', '55', 0, 'andreas', 'solicitado', 'Pokémon Sword', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/842.png'), 
('Frosmoth', 'Ice Beam', 'Bug Buzz', 'Quiver Dance', 'Giga Drain', 'Ice Scales', '59', 1, 'andreas', 'ofrecido', 'Pokémon Shield', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/873.png'), 
('Coalossal', 'Heat Crash', 'Stone Edge', 'Earthquake', 'Flame Charge', 'Steam Engine', '57', 0, 'seogonzalez', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/839.png'), 
('Arctozolt', 'Bolt Beak', 'Freeze-Dry', 'Ancient Power', 'Avalanche', 'Volt Absorb', '55', 1, 'seogonzalez', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/881.png'), 
('Copperajah', 'Heavy Slam', 'Earthquake', 'Iron Head', 'Stone Edge', 'Sheer Force', '61', 1, 'pokebarter', 'solicitado', 'Pokémon Sword', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/879.png'), 
('Dracozolt', 'Bolt Beak', 'Outrage', 'Dragon Claw', 'Aerial Ace', 'Volt Absorb', '63', 1, 'pokebarter', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/880.png'), 
('Flapple', 'Dragon Pulse', 'Grav Apple', 'Acrobatics', 'Leech Seed', 'Ripen', '55', 0, 'badgyal', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/841.png'), 
('Arctovish', 'Freeze-Dry', 'Ancient Power', 'Avalanche', 'Icicle Crash', 'Water Absorb', '57', 1, 'badgyal', 'ofrecido', 'Pokémon Shield', '', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/883.png'), 
('Talonflame', 'Brave Bird', 'Flare Blitz', 'Roost', 'Swords Dance', 'Gale Wings', '61', 0, 'luisg', 'solicitado', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/663.png'), 
('Garchomp', 'Earthquake', 'Dragon Claw', 'Fire Fang', 'Swords Dance', 'Sand Veil', '67', 1, 'sofiaf', 'ofrecido', 'Pokémon Ultra Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/445.png'), 
('Lucario', 'Close Combat', 'Aura Sphere', 'Flash Cannon', '', 'Inner Focus', '61', 1, 'sofiaf', 'solicitado', 'Pokémon Ultra Moon', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/448.png'), 
('Torterra', 'Wood Hammer', 'Earthquake', 'Stone Edge', 'Synthesis', 'Overgrow', '59', 1, 'seogonzalez', 'ofrecido', 'Pokémon Alpha Sapphire', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/389.png'), 
('Hippowdon', 'Earthquake', 'Stealth Rock', 'Slack Off', 'Whirlwind', 'Sand Stream', '53', 0, 'seogonzalez', 'solicitado', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/450.png'), 
('Magnezone', 'Thunderbolt', 'Flash Cannon', 'Volt Switch', 'Thunder Wave', 'Magnet Pull', '57', 1, 'pokebarter', 'ofrecido', 'Pokémon Ultra Sun', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/462.png'), 
('Scizor', 'Bullet Punch', 'U-turn', 'Roost', 'Swords Dance', 'Technician', '59', 1, 'pokebarter', 'solicitado', 'Pokémon Ultra Moon', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/212.png'), 
('Espeon', 'Psychic', 'Shadow Ball', 'Calm Mind', 'Dazzling Gleam', 'Magic Bounce', '55', 0, 'andreas', 'ofrecido', 'Pokémon X', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/196.png'), 
('Krookodile', 'Earthquake', 'Crunch', 'Outrage', 'Stone Edge', 'Moxie', '63', 0, 'andreas', 'solicitado', 'Pokémon Y', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/553.png'), 
('Swampert', 'Earthquake', 'Waterfall', 'Ice Punch', '', 'Torrent', '47', 0, 'migueld', 'ofrecido', 'Pokémon Omega Ruby', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png'), 
('Lucario', 'Close Combat', 'Aura Sphere', 'Flash Cannon', '', 'Inner Focus', '61', 0, 'migueld', 'solicitado', 'Pokémon Alpha Sapphire', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png'), 
('Salamence', 'Dragon Claw', 'Dragon Dance', 'Earthquake', 'Fire Blast', '', '65', 1, 'luisg', 'ofrecido', 'Pokémon Ultra Moon', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/373.png'), 
('Swampert', 'Earthquake', 'Waterfall', 'Ice Punch', '', '', '47', 0, 'jorgeh', 'solicitado', 'Pokémon Ultra Moon', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png'), 
('Lucario', 'Close Combat', 'Aura Sphere', 'Flash Cannon', '', '', '61', 1, 'jorgeh', 'ofrecido', 'Pokémon Alpha Sapphire', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/448.png'), 
('Gyarados', 'Waterfall', 'Ice Fang', 'Earthquake', 'Dragon Dance', '', '59', 0, 'sofiaf', 'solicitado', 'Pokémon Shield', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/130.png'), 
('Sylveon', 'Hyper Voice', 'Moonblast', 'Shadow Ball', 'Wish', '', '49', 1, 'sofiaf', 'ofrecido', 'Pokémon Omega Ruby', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/700.png'), 
('Charizard', 'Flamethrower', 'Dragon Claw', 'Air Slash', 'Roost', '', '55', 0, 'seogonzalez', 'solicitado', 'Pokemon Y', '-', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png'), 
('Swellow', 'Aerial Ace', 'Brave Bird', '', '', '', '55', 0, 'jorgeh', 'solicitado', 'Pokémon X', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/277.png'), 
('Linoone', 'Slash', 'Shadow Claw', '', '', '', '49', 1, 'jorgeh', 'ofrecido', 'Pokémon Y', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/264.png'), 
('Gardevoir', 'Psychic', 'Moonblast', '', '', '', '59', 1, 'sofiaf', 'solicitado', 'Pokémon X', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/282.png'), 
('Mawile', 'Iron Head', 'Play Rough', '', '', '', '53', 0, 'sofiaf', 'ofrecido', 'Pokémon Y', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/303.png'), 
('Crobat', 'Air Slash', 'Poison Fang', '', '', '', '57', 0, 'luciar', 'solicitado', 'Pokémon X', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/169.png'), 
('Donphan', 'Earthquake', 'Rollout', '', '', '', '51', 1, 'luciar', 'ofrecido', 'Pokémon Y', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/232.png'), 
('Ludicolo', 'Hydro Pump', 'Giga Drain', '', '', '', '55', 0, 'seogonzalez', 'solicitado', 'Pokémon X', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/272.png'),
('Toxtricity Low Key', 'Boomburst', 'Overdrive', 'Sludge Bomb', 'Volt Switch', 'Punk Rock', '59', 1, 'seogonzalez', 'ofrecido', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10184.png'), 
('Corviknight', 'Brave Bird', 'Iron Head', 'Roost', 'Body Press', 'Pressure', '63', 0, 'andreas', 'solicitado', 'Pokémon Ultra Sun', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/823.png'), 
('Frosmoth', 'Ice Beam', 'Bug Buzz', 'Quiver Dance', 'Giga Drain', 'Ice Scales', '59', 1, 'andreas', 'ofrecido', 'Pokémon Ultra Moon', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/873.png'), 
('Grapploct', 'Octolock', 'Close Combat', 'Liquidation', 'Sucker Punch', 'Limber', '61', 1, 'migueld', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/853.png'), 
('Toxtricity Amped', 'Boomburst', 'Overdrive', 'Sludge Bomb', 'Volt Switch', 'Punk Rock', '59', 1, 'migueld', 'ofrecido', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/849.png'), 
('Corviknight', 'Brave Bird', 'Iron Head', 'Roost', 'Body Press', 'Pressure', '63', 0, 'jorgeh', 'solicitado', 'Pokémon Ultra Sun', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/823.png'), 
('Frosmoth', 'Ice Beam', 'Bug Buzz', 'Quiver Dance', 'Giga Drain', 'Ice Scales', '59', 1, 'jorgeh', 'ofrecido', 'Pokémon Ultra Moon', 'F', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/873.png'), 
('Grapploct', 'Octolock', 'Close Combat', 'Liquidation', 'Sucker Punch', 'Limber', '61', 0, 'sofiaf', 'solicitado', 'Pokémon Sword', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/853.png'), 
('Toxtricity Amped', 'Boomburst', 'Overdrive', 'Sludge Bomb', 'Volt Switch', 'Punk Rock', '59', 1, 'sofiaf', 'ofrecido', 'Pokémon Shield', 'M', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/849.png');
 